diff -Nrq outputs/ newoutputs/v1 > finalresults/diff_output_vo_v1
diff -Nrq outputs/ newoutputs/v2 > finalresults/diff_output_vo_v2
diff -Nrq outputs/ newoutputs/v3 > finalresults/diff_output_vo_v3
diff -Nrq outputs/ newoutputs/v4 > finalresults/diff_output_vo_v4
diff -Nrq outputs/ newoutputs/v5 > finalresults/diff_output_vo_v5
diff -Nrq outputs/ newoutputs/v6 > finalresults/diff_output_vo_v6
diff -Nrq outputs/ newoutputs/v7 > finalresults/diff_output_vo_v7
diff -Nrq outputs/ newoutputs/v8 > finalresults/diff_output_vo_v8
diff -Nrq outputs/ newoutputs/v9 > finalresults/diff_output_vo_v9
diff -Nrq outputs/ newoutputs/v10 > finalresults/diff_output_vo_v10
diff -Nrq outputs/ newoutputs/v11 > finalresults/diff_output_vo_v11
diff -Nrq outputs/ newoutputs/v12 > finalresults/diff_output_vo_v12
diff -Nrq outputs/ newoutputs/v13 > finalresults/diff_output_vo_v13
diff -Nrq outputs/ newoutputs/v14 > finalresults/diff_output_vo_v14
diff -Nrq outputs/ newoutputs/v15 > finalresults/diff_output_vo_v15
diff -Nrq outputs/ newoutputs/v16 > finalresults/diff_output_vo_v16
diff -Nrq outputs/ newoutputs/v17 > finalresults/diff_output_vo_v17
diff -Nrq outputs/ newoutputs/v18 > finalresults/diff_output_vo_v18
diff -Nrq outputs/ newoutputs/v19 > finalresults/diff_output_vo_v19
diff -Nrq outputs/ newoutputs/v20 > finalresults/diff_output_vo_v20
diff -Nrq outputs/ newoutputs/v21 > finalresults/diff_output_vo_v21
diff -Nrq outputs/ newoutputs/v22 > finalresults/diff_output_vo_v22
diff -Nrq outputs/ newoutputs/v23 > finalresults/diff_output_vo_v23
diff -Nrq outputs/ newoutputs/v24 > finalresults/diff_output_vo_v24
diff -Nrq outputs/ newoutputs/v25 > finalresults/diff_output_vo_v25
diff -Nrq outputs/ newoutputs/v26 > finalresults/diff_output_vo_v26
diff -Nrq outputs/ newoutputs/v27 > finalresults/diff_output_vo_v27
diff -Nrq outputs/ newoutputs/v28 > finalresults/diff_output_vo_v28
diff -Nrq outputs/ newoutputs/v29 > finalresults/diff_output_vo_v29
diff -Nrq outputs/ newoutputs/v30 > finalresults/diff_output_vo_v30
diff -Nrq outputs/ newoutputs/v31 > finalresults/diff_output_vo_v31
diff -Nrq outputs/ newoutputs/v32 > finalresults/diff_output_vo_v32
