# chaonin 02.16.2020
all:
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v1/replace.c v1/instrument.c -o v1/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v2/replace.c v2/instrument.c -o v2/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v3/replace.c v3/instrument.c -o v3/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v4/replace.c v4/instrument.c -o v4/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v5/replace.c v5/instrument.c -o v5/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v6/replace.c v6/instrument.c -o v6/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v7/replace.c v7/instrument.c -o v7/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v8/replace.c v8/instrument.c -o v8/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v9/replace.c v9/instrument.c -o v9/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v10/replace.c v10/instrument.c -o v10/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v11/replace.c v11/instrument.c -o v11/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v12/replace.c v12/instrument.c -o v12/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v13/replace.c v13/instrument.c -o v13/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v14/replace.c v14/instrument.c -o v14/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v15/replace.c v15/instrument.c -o v15/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v16/replace.c v16/instrument.c -o v16/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v17/replace.c v17/instrument.c -o v17/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v18/replace.c v18/instrument.c -o v18/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v19/replace.c v19/instrument.c -o v19/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v20/replace.c v20/instrument.c -o v20/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v21/replace.c v21/instrument.c -o v21/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v22/replace.c v22/instrument.c -o v22/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v23/replace.c v23/instrument.c -o v23/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v24/replace.c v24/instrument.c -o v24/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v25/replace.c v25/instrument.c -o v25/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v26/replace.c v26/instrument.c -o v26/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v27/replace.c v27/instrument.c -o v27/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v28/replace.c v28/instrument.c -o v28/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v29/replace.c v29/instrument.c -o v29/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v30/replace.c v30/instrument.c -o v30/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v31/replace.c v31/instrument.c -o v31/replace.exe
	gcc -fprofile-arcs -ftest-coverage -g -finstrument-functions v32/replace.c v32/instrument.c -o v32/replace.exe

clean:
	rm v1/replace.exe
	rm v2/replace.exe
	rm v3/replace.exe
	rm v4/replace.exe
	rm v5/replace.exe
	rm v6/replace.exe
	rm v7/replace.exe
	rm v8/replace.exe
	rm v9/replace.exe
	rm v10/replace.exe
	rm v11/replace.exe
	rm v12/replace.exe
	rm v13/replace.exe
	rm v14/replace.exe
	rm v15/replace.exe
	rm v16/replace.exe
	rm v17/replace.exe
	rm v18/replace.exe
	rm v19/replace.exe
	rm v20/replace.exe
	rm v21/replace.exe
	rm v22/replace.exe
	rm v23/replace.exe
	rm v24/replace.exe
	rm v25/replace.exe
	rm v26/replace.exe
	rm v27/replace.exe
	rm v28/replace.exe
	rm v29/replace.exe
	rm v30/replace.exe
	rm v31/replace.exe
	rm v32/replace.exe
